model_params:
  name: 'simple_flow'
  in_channels: 3
  latent_dim: 128


data_params:
  data_path: "./cifar10/"
  batch_size: 64 
  image_size: 64
  num_workers: 4

exp_params:
  LR: 0.001
  manual_seed: 1265

trainer_params:
  gpus: [0]
  epoch: 100

logging_params:
  save_dir: "./logs/simple_flow/"
  name: "simple_flow"